import pandas as pd
import numpy as np
import json
from typing import List, Optional
from fastapi import FastAPI, Depends, HTTPException, status, APIRouter, BackgroundTasks
from fastapi.security import OAuth2PasswordRequestForm
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from sqlalchemy import func, desc, text, cast, Date
from datetime import datetime, date, timedelta

from src.db import database, models
from src.api import schemas, auth

from src.core.etl import get_user_data
from src.core.feature_engineering import generate_all_features
from src.core.anomaly_detection import run_anomaly_detection
from src.core.risk_prediction import predict_academic_risk
from src.core.recommendation_engine import RecommendationEngine

app = FastAPI(
    title="Student Digital Twin API",
    description="Backend API for the Student Edition Digital Twin project.",
    version="1.5.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

router = APIRouter(prefix="/api/v1")


# =============================================
# DAILY GOALS GENERATOR
# =============================================
def generate_daily_goals(db: Session, user_id: int):
    today = date.today()

    # Optional: If you want goals to dynamically update when user submits new data on the same day,
    # you can delete UNCOMPLETED goals for today before generating new ones.
    # db.query(models.Goal).filter(models.Goal.user_id == user_id, models.Goal.date == today, models.Goal.completed == False).delete()
    # db.commit()

    existing_today = db.query(models.Goal).filter(
        models.Goal.user_id == user_id,
        models.Goal.date == today
    ).count()

    if existing_today > 0:
        return  # Goals already exist for today

    # 1. Fetch the latest AI Insights (Recommendations) generated by the engine
    latest_recs = db.query(models.Recommendation).filter(
        models.Recommendation.user_id == user_id
    ).all()

    dynamic_goals = []

    # 2. Extract the specific goals attached to those insights
    for rec in latest_recs:
        if rec.goals:
            try:
                # rec.goals is stored as a JSON string in the database
                goals_list = json.loads(rec.goals)
                dynamic_goals.extend(goals_list)
            except Exception as e:
                print(f"Error parsing goals JSON: {e}")

    # 3. Fallbacks in case the user is perfectly healthy ("Resilient Baseline")
    fallbacks = [
        "Maintain your current healthy habits and routines.",
        "Take a 15-minute walk outdoors for mental clarity.",
        "Use this stable state to focus on high-priority tasks."
    ]

    # 4. Remove duplicates (in case two insights suggest the same goal) while keeping order
    seen = set()
    unique_goals = []
    for g in dynamic_goals + fallbacks:
        if g not in seen:
            unique_goals.append(g)
            seen.add(g)

    # 5. Limit to exactly 3 goals
    final_goals = unique_goals[:3]

    # 6. Save to database
    for text in final_goals:
        db.add(models.Goal(user_id=user_id, date=today, text=text, completed=False))

    db.commit()
# =============================================
# DAY STREAK CALCULATOR
# =============================================
def calculate_day_streak(db: Session, user_id: int) -> int:
    vitals_dates = db.query(func.date(models.Vitals.ts)).filter(models.Vitals.user_id == user_id).distinct().all()
    lifestyle_dates = db.query(models.Lifestyle.date).filter(models.Lifestyle.user_id == user_id).distinct().all()
    academic_dates = db.query(models.Academic.date).filter(models.Academic.user_id == user_id).distinct().all()
    activity_dates = db.query(models.Activity.date).filter(models.Activity.user_id == user_id).distinct().all()

    all_dates = set()
    for row in vitals_dates:
        if row[0]:
            d = row[0]
            all_dates.add(d if isinstance(d, date) else d.date() if hasattr(d, 'date') else d)
    for row in lifestyle_dates + academic_dates + activity_dates:
        if row[0]:
            all_dates.add(row[0])

    if not all_dates:
        return 0

    sorted_dates = sorted(all_dates, reverse=True)
    streak = 0
    check_date = date.today()

    if sorted_dates[0] < check_date:
        check_date = sorted_dates[0]

    for d in sorted_dates:
        if d == check_date:
            streak += 1
            check_date -= timedelta(days=1)
        elif d < check_date:
            break

    return streak


# =============================================
# ACHIEVEMENTS CALCULATOR
# =============================================
def calculate_achievements(db: Session, user_id: int, health_score: float, pending_count: int) -> list:
    achievements = []

    if pending_count <= 1:
        achievements.append({"icon": "fas fa-dove", "title": "Early Bird", "description": "1 or fewer pending goals!"})

    streak = calculate_day_streak(db, user_id)
    all_dates = set()
    for row in db.query(func.date(models.Vitals.ts)).filter(models.Vitals.user_id == user_id).distinct().all():
        if row[0]: all_dates.add(row[0] if isinstance(row[0], date) else row[0])
    for row in db.query(models.Lifestyle.date).filter(models.Lifestyle.user_id == user_id).distinct().all():
        if row[0]: all_dates.add(row[0])
    for row in db.query(models.Academic.date).filter(models.Academic.user_id == user_id).distinct().all():
        if row[0]: all_dates.add(row[0])
    for row in db.query(models.Activity.date).filter(models.Activity.user_id == user_id).distinct().all():
        if row[0]: all_dates.add(row[0])

    if all_dates:
        latest_date = max(all_dates)
        days_gap = (date.today() - latest_date).days
        if streak >= 3 and days_gap < 3:
            achievements.append({"icon": "fas fa-chart-line", "title": "Consistent Tracker", "description": f"{streak} day streak!"})

    if health_score > 70:
        achievements.append({"icon": "fas fa-heart", "title": "Health Champion", "description": "Health score above 70!"})

    return achievements


# =============================================
# BACKGROUND ANALYSIS
# =============================================
def run_full_analysis(db: Session, user: models.User):
    print(f"Running background analysis for user {user.user_id}...")
    try:
        df = get_user_data(db, user.user_id)
        if df is None or df.empty: return

        df_features = generate_all_features(df)
        if df_features is None or df_features.empty: return

        alerts = run_anomaly_detection(df_features)
        formatted_anomalies = []
        if alerts:
            for alert_str in alerts:
                today = date.today()
                existing_alert = db.query(models.Alert).filter(
                    models.Alert.user_id == user.user_id, models.Alert.alert_type == alert_str,
                    func.date(models.Alert.alert_ts) == today).first()
                if not existing_alert:
                    db.add(models.Alert(user_id=user.user_id, alert_type=alert_str, resolved_flag=False))
                if 'heart' in alert_str.lower() or 'hr' in alert_str.lower():
                    formatted_anomalies.append({'metric': 'heart_rate'})
                else:
                    formatted_anomalies.append({'metric': alert_str})

        risk_score, risk_label = predict_academic_risk(df_features)
        db.add(models.Prediction(user_id=user.user_id, model="RandomForest_v1",
                                 risk_score=float(risk_score), label=risk_label, pred_ts=datetime.now()))

        recommender = RecommendationEngine()
        latest_features = {
            "stress_score": float(df_features.iloc[-1].get('stress_score', 5.0)),
            "sleep_hrs": float(df_features.iloc[-1].get('sleep_hrs', 7.0)),
            "study_hrs": float(df_features.iloc[-1].get('study_hrs', 5.0)),
            "hr": float(df_features.iloc[-1].get('hr', 75.0)),
            # Removed steps mapping here entirely to clean up
            "water_glasses": int(df_features.iloc[-1].get('water_glasses', 6.0))
        }

        insights = recommender.generate_all_insights(
            features=latest_features,
            anomalies=formatted_anomalies,
            risk_score=float(risk_score)
        )

        # Delete old recommendations and save ALL new ones
        db.query(models.Recommendation).filter(models.Recommendation.user_id == user.user_id).delete()

        for insight in insights:
            db.add(models.Recommendation(
                user_id=user.user_id,
                # Map the new 'severity' key to the database's 'type' column
                type=insight.get('severity', insight.get('type', 'info')),

                # Safely grab the text fields
                title=insight.get('title', 'Health Insight'),
                explanation=insight.get('explanation', ''),

                # Safely grab the lists and convert to JSON
                causes=json.dumps(insight.get('causes', [])),

                # Check for either 'health_goals' or 'goals' just to be 100% safe
                goals=json.dumps(insight.get('health_goals', insight.get('goals', [])))
            ))
        db.commit()
    except Exception as e:
        db.rollback()
        print(f"Background analysis error: {e}")

# --- Auth Endpoints ---
@router.post("/auth/register", response_model=schemas.User)
def register_user(user: schemas.UserCreate, db: Session = Depends(database.get_db)):
    db_user = auth.get_user(db, email=user.email)
    if db_user: raise HTTPException(status_code=400, detail="Email already registered")
    new_user = models.User(email=user.email, hashed_password=auth.get_password_hash(user.password),
                           username=user.username, first_name=user.first_name, last_name=user.last_name, consent=True)
    db.add(new_user)
    db.commit()
    db.refresh(new_user)
    return new_user


@router.post("/auth/token", response_model=schemas.Token)
def login_for_access_token(form_data: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(database.get_db)):
    user = auth.get_user(db, email=form_data.username)
    if not user or not auth.verify_password(form_data.password, user.hashed_password):
        raise HTTPException(status_code=401, detail="Incorrect credentials")
    access_token = auth.create_access_token(data={"sub": str(user.user_id)})
    return {"access_token": access_token, "token_type": "bearer"}


# --- Data Entry Endpoints ---
@router.post("/data/vitals")
def submit_vitals(data: schemas.VitalsData, bg: BackgroundTasks, db: Session = Depends(database.get_db),
                  user=Depends(auth.get_current_user)):
    record_ts = data.ts if data.ts else datetime.now()
    record_date = record_ts.date()
    existing = db.query(models.Vitals).filter(models.Vitals.user_id == user.user_id, func.date(models.Vitals.ts) == record_date).first()
    if existing:
        for k, v in data.model_dump(exclude_unset=True).items(): setattr(existing, k, v)
        existing.ts = record_ts
    else:
        dump = data.model_dump()
        dump['ts'] = record_ts
        db.add(models.Vitals(user_id=user.user_id, **dump))
    db.commit()
    bg.add_task(run_full_analysis, db, user)
    return {"status": "success"}


@router.post("/data/lifestyle")
def submit_lifestyle(data: schemas.LifestyleData, bg: BackgroundTasks, db: Session = Depends(database.get_db),
                     user=Depends(auth.get_current_user)):
    existing = db.query(models.Lifestyle).filter(models.Lifestyle.user_id == user.user_id, models.Lifestyle.date == data.date).first()
    if existing:
        for k, v in data.model_dump().items(): setattr(existing, k, v)
    else:
        db.add(models.Lifestyle(user_id=user.user_id, **data.model_dump()))
    db.commit()
    bg.add_task(run_full_analysis, db, user)
    return {"status": "success"}


@router.post("/data/activity")
def submit_activity(data: schemas.ActivityData, bg: BackgroundTasks, db: Session = Depends(database.get_db),
                    user=Depends(auth.get_current_user)):
    existing = db.query(models.Activity).filter(models.Activity.user_id == user.user_id, models.Activity.date == data.date).first()
    if existing:
        for k, v in data.model_dump().items(): setattr(existing, k, v)
    else:
        db.add(models.Activity(user_id=user.user_id, **data.model_dump()))
    db.commit()
    bg.add_task(run_full_analysis, db, user)
    return {"status": "success"}


@router.post("/data/academic")
def submit_academic(data: schemas.AcademicData, bg: BackgroundTasks, db: Session = Depends(database.get_db),
                    user=Depends(auth.get_current_user)):
    existing = db.query(models.Academic).filter(models.Academic.user_id == user.user_id, models.Academic.date == data.date).first()
    if existing:
        for k, v in data.model_dump(exclude_unset=True).items(): setattr(existing, k, v)
    else:
        db.add(models.Academic(user_id=user.user_id, **data.model_dump()))
    db.commit()
    bg.add_task(run_full_analysis, db, user)
    return {"status": "success"}


# =============================================
# GOALS ENDPOINTS
# =============================================
@router.get("/goals/active")
def get_active_goals(db: Session = Depends(database.get_db), user=Depends(auth.get_current_user)):
    generate_daily_goals(db, user.user_id)
    today = date.today()

    all_pending = db.query(models.Goal).filter(
        models.Goal.user_id == user.user_id, models.Goal.completed == False
    ).order_by(models.Goal.date.desc(), models.Goal.id).all()

    today_pending = db.query(models.Goal).filter(
        models.Goal.user_id == user.user_id, models.Goal.date == today, models.Goal.completed == False).count()
    previous_pending = db.query(models.Goal).filter(
        models.Goal.user_id == user.user_id, models.Goal.date < today, models.Goal.completed == False).count()

    goals_list = [{"id": g.id, "text": g.text, "date": g.date.isoformat(), "completed": g.completed,
                   "is_today": g.date == today} for g in all_pending]

    return {"goals": goals_list, "today_pending": today_pending, "previous_pending": previous_pending,
            "active_count": len(all_pending), "no_pending": previous_pending == 0}


@router.put("/goals/{goal_id}/complete")
def complete_goal(goal_id: int, db: Session = Depends(database.get_db), user=Depends(auth.get_current_user)):
    goal = db.query(models.Goal).filter(models.Goal.id == goal_id, models.Goal.user_id == user.user_id).first()
    if not goal: raise HTTPException(status_code=404, detail="Goal not found")
    goal.completed = True
    db.commit()

    # Return updated count for frontend sync
    remaining = db.query(models.Goal).filter(
        models.Goal.user_id == user.user_id, models.Goal.completed == False).count()
    return {"status": "success", "goal_id": goal_id, "active_count": remaining}


# =============================================
# PROFILE STATS ENDPOINT
# =============================================
@router.get("/profile/stats")
def get_profile_stats(db: Session = Depends(database.get_db), user=Depends(auth.get_current_user)):
    latest_pred = db.query(models.Prediction).filter(
        models.Prediction.user_id == user.user_id).order_by(desc(models.Prediction.pred_ts)).first()

    v_count = db.query(func.count(models.Vitals.id)).filter(models.Vitals.user_id == user.user_id).scalar() or 0
    l_count = db.query(func.count(models.Lifestyle.id)).filter(models.Lifestyle.user_id == user.user_id).scalar() or 0
    a_count = db.query(func.count(models.Academic.id)).filter(models.Academic.user_id == user.user_id).scalar() or 0
    act_count = db.query(func.count(models.Activity.id)).filter(models.Activity.user_id == user.user_id).scalar() or 0
    total_entries = v_count + l_count + a_count + act_count

    df = get_user_data(db, user.user_id)
    current_wellness = 5.0
    if df is not None and not df.empty:
        try:
            df_features = generate_all_features(df)
            if not df_features.empty:
                current_wellness = float(df_features.iloc[-1].get('WellnessScore', 5.0))
        except: pass

    ai_risk = float(latest_pred.risk_score if latest_pred else 0.2)
    health_score = round(min(max((current_wellness * 7) + ((1 - ai_risk) * 30), 0), 100), 1)
    if health_score > 75:
        display_label = "Optimal"
    elif health_score >= 60:
        display_label = "Normal"
    else:
        display_label = "At Risk"

    day_streak = calculate_day_streak(db, user.user_id)
    generate_daily_goals(db, user.user_id)

    today = date.today()
    pending_goals = db.query(models.Goal).filter(
        models.Goal.user_id == user.user_id, models.Goal.completed == False
    ).order_by(models.Goal.date.desc(), models.Goal.id).all()

    previous_pending = db.query(models.Goal).filter(
        models.Goal.user_id == user.user_id, models.Goal.date < today, models.Goal.completed == False).count()

    goals_list = [{"id": g.id, "text": g.text, "date": g.date.isoformat(), "completed": g.completed,
                   "is_today": g.date == today} for g in pending_goals]

    achievements = calculate_achievements(db, user.user_id, health_score, previous_pending)

    today_lifestyle = db.query(models.Lifestyle).filter(
        models.Lifestyle.user_id == user.user_id, models.Lifestyle.date == today).first()
    all_lifestyle = db.query(models.Lifestyle).filter(models.Lifestyle.user_id == user.user_id).all()

    current_sleep = float(today_lifestyle.sleep_hrs) if today_lifestyle and today_lifestyle.sleep_hrs else 0.0
    sleep_target = 8.0
    if all_lifestyle:
        avg_sleep = sum(l.sleep_hrs or 0 for l in all_lifestyle) / len(all_lifestyle)
        sleep_progress = min(round((avg_sleep / sleep_target) * 100, 1), 100)
    else:
        sleep_progress = 0

    current_stress = float(today_lifestyle.stress_score) if today_lifestyle and today_lifestyle.stress_score else 0.0
    stress_target = 4.0
    if all_lifestyle:
        avg_stress = sum(l.stress_score or 0 for l in all_lifestyle) / len(all_lifestyle)
        stress_progress = 100.0 if avg_stress <= stress_target else min(round((stress_target / avg_stress) * 100, 1), 100)
    else:
        stress_progress = 0

        # ... everything above this in your get_profile_stats function stays the same ...

        return {
            "health_score": health_score,
            "health_label": display_label,  # 🚀 Added to fix the 'at_risk' contradiction
            "total_entries": total_entries,
            "day_streak": day_streak,
            "active_goals": len(pending_goals),
            "achievements": achievements,
            "health_goals": [
                {
                    "title": "Improve Sleep Quality",
                    "target": sleep_target,
                    "current": current_sleep,
                    "progress": sleep_progress,
                    "unit": "hours"
                },
                {
                    "title": "Reduce Stress Level",
                    "target": stress_target,
                    "current": current_stress,
                    "progress": stress_progress,
                    "unit": "stress level"
                }
            ],
            "pending_goals": goals_list,
            "no_pending": previous_pending == 0
        }

# =============================================
# ANALYTICS SUMMARY
# =============================================
@router.get("/analytics/summary")
def get_analytics_summary(db: Session = Depends(database.get_db), user=Depends(auth.get_current_user)):
    # 1. Fetch data
    latest = db.query(models.Prediction).filter(models.Prediction.user_id == user.user_id).order_by(
        desc(models.Prediction.pred_ts)).first()
    active_alerts = db.query(models.Alert).filter(models.Alert.user_id == user.user_id,
                                                  models.Alert.resolved_flag == False).all()

    v = db.query(func.avg(models.Vitals.hr), func.count(models.Vitals.id)).filter(
        models.Vitals.user_id == user.user_id).first()
    l = db.query(func.avg(models.Lifestyle.sleep_hrs), func.avg(models.Lifestyle.stress_score),
                 func.count(models.Lifestyle.id)).filter(models.Lifestyle.user_id == user.user_id).first()
    a = db.query(func.avg(models.Academic.study_hrs), func.count(models.Academic.id)).filter(
        models.Academic.user_id == user.user_id).first()

    # 2. Calculate Wellness and Health Score
    df = get_user_data(db, user.user_id)
    chart_data = []
    current_wellness = 5.0  # Default value

    if df is not None and not df.empty:
        try:
            df_features = generate_all_features(df)
            if not df_features.empty:
                current_wellness = float(df_features.iloc[-1].get('WellnessScore', 5.0))
            chart_data = df_features.replace({np.nan: None}).to_dict(orient='records')
        except Exception as e:
            print(f"Chart error: {e}")

    ai_risk = float(latest.risk_score if latest else 0.2)
    final_health_score = round(min(max((current_wellness * 7) + ((1 - ai_risk) * 30), 0), 100), 1)

    # 🚀 THE LOGIC FIX: Determine label based on your specific score rules
    if final_health_score > 75:
        display_label = "Optimal"
    elif final_health_score >= 60:
        display_label = "Normal"
    else:
        display_label = "At Risk"

    # 3. Recommendations and Goals
    db_recs = db.query(models.Recommendation).filter(models.Recommendation.user_id == user.user_id).all()
    parsed_recs = [{"id": r.id, "type": r.type, "title": r.title, "explanation": r.explanation,
                    "causes": json.loads(r.causes) if r.causes else [], "goals": json.loads(r.goals) if r.goals else []}
                   for r in db_recs]

    generate_daily_goals(db, user.user_id)
    active_goals_count = db.query(models.Goal).filter(
        models.Goal.user_id == user.user_id, models.Goal.completed == False).count()

    return {
        "health_score": final_health_score,
        "risk_score": ai_risk,
        "risk_label": display_label,  # This fixes the 78.8 "at_risk" issue
        "timestamp": latest.pred_ts if latest else datetime.now(),
        "alerts": [al.alert_type for al in active_alerts],
        "vitals": {"avg_heart_rate": round(float(v[0] or 0), 1), "count": v[1] or 0},
        "lifestyle": {"avg_sleep": round(float(l[0] or 0), 1), "avg_stress": round(float(l[1] or 0), 1),
                      "count": l[2] or 0},
        "academic": {"avg_study_hours": round(float(a[0] or 0), 1), "count": a[1] or 0},
        "chart_data": chart_data,
        "ai_metadata": {"is_anomaly": len(active_alerts) > 0, "system_status": "Operational"},
        "recommendations": parsed_recs,
        "active_goals": active_goals_count
    }
# --- Standard Getters ---
@router.get("/data/vitals", response_model=schemas.VitalsResponse)
def get_vitals(db: Session = Depends(database.get_db), user=Depends(auth.get_current_user)):
    return {"results": db.query(models.Vitals).filter(models.Vitals.user_id == user.user_id).all()}

@router.get("/data/lifestyle", response_model=schemas.LifestyleResponse)
def get_lifestyle(db: Session = Depends(database.get_db), user=Depends(auth.get_current_user)):
    return {"results": db.query(models.Lifestyle).filter(models.Lifestyle.user_id == user.user_id).all()}

@router.get("/data/academic", response_model=schemas.AcademicResponse)
def get_academic_history(db: Session = Depends(database.get_db), user=Depends(auth.get_current_user)):
    return {"results": db.query(models.Academic).filter(models.Academic.user_id == user.user_id).all()}

@router.get("/data/activity", response_model=schemas.ActivityResponse)
def get_activity(db: Session = Depends(database.get_db), user=Depends(auth.get_current_user)):
    return {"results": db.query(models.Activity).filter(models.Activity.user_id == user.user_id).all()}

@router.get("/users/me", response_model=schemas.User)
def read_users_me(user: models.User = Depends(auth.get_current_user)):
    return user


# =============================================
# ✅ NEW: Update User Profile
# =============================================
@router.put("/users/me", response_model=schemas.User)
def update_user_profile(update_data: schemas.UserUpdate, db: Session = Depends(database.get_db),
                        user: models.User = Depends(auth.get_current_user)):
    if update_data.first_name is not None:
        user.first_name = update_data.first_name
    if update_data.last_name is not None:
        user.last_name = update_data.last_name
    if update_data.email is not None:
        existing = db.query(models.User).filter(models.User.email == update_data.email, models.User.user_id != user.user_id).first()
        if existing: raise HTTPException(status_code=400, detail="Email already in use")
        user.email = update_data.email
    if update_data.avatar is not None:
        user.avatar = update_data.avatar
    if update_data.theme is not None:
        user.theme = update_data.theme
    db.commit()
    db.refresh(user)
    return user


app.include_router(router)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)